version : '3'

services: 
  lb:
    image: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  nodeapp1:
    image: nodeapp
    environment:
      - APPID=nodeapp1(port:1111)
  nodeapp2:
    image: nodeapp
    environment:
      - APPID=nodeapp2(port:2222)
  nodeapp3:
    image: nodeapp
    environment:
      - APPID=nodeapp3(port:3333)